# Remote server parameters
# server_url = "http://localhost"
server_url = "https://bifrost.oberon-server.it"
#port = 3000
port = 443

# local filesystem mount point (absolute path)
mount_point = "/mnt/bifrost"

# Timeout in secondi (se usi std::time::Duration) o nanosecondi (se usi chrono::Duration)
# Per std::time::Duration: 60 secondi
timeout = { secs = 60, nanos = 0 }