name: Build & Deploy bifrost-server

on:
  push:
    branches:
      - main
    paths:
      - "server/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ${{ secrets.DEPLOY_DIRECTORY }}
            echo "Pulling latest changes..."
            git pull origin main
            cd server
            echo "Removing dist folder..."
            rm -rf dist
            echo "Installing dependencies..."
            npm install
            echo "Building project..."
            npm run build
            echo "Copying .env file..."
            cp .env dist/
            echo "Restarting bifrost.service..."
            sudo systemctl restart bifrost.service
